{"name": "Неавторизованный пользователь не может создать заказ", "status": "failed", "statusDetails": {"message": "AssertionError: assert 200 == 401\n +  where 200 = <Response [200]>.status_code", "trace": "self = <tests.test_order.TestOrder object at 0x0000018FBCFBCDD0>\ningredients = [{'__v': 0, '_id': '61c0c5a71d1f82001bdaaa6d', 'calories': 643, 'carbohydrates': 85, ...}, {'__v': 0, '_id': '61c0c5a7...arbohydrates': 40, ...}, {'__v': 0, '_id': '61c0c5a71d1f82001bdaaa6e', 'calories': 643, 'carbohydrates': 85, ...}, ...]\n\n    @allure.title('Неавторизованный пользователь не может создать заказ')\n    @allure.description('Проверка: статус 401, заказ без авторизации нельзя создать.')\n    def test_create_order_without_auth(self, ingredients):\n        order_data = {\n            \"ingredients\": [ingredients[0]['_id'], ingredients[1]['_id']]\n        }\n    \n        response = requests.post(f\"{url.MAIN_URL}/api/orders\", data=order_data)\n    \n>       assert response.status_code == 401\nE       assert 200 == 401\nE        +  where 200 = <Response [200]>.status_code\n\ntests\\test_order.py:34: AssertionError"}, "description": "Проверка: статус 401, заказ без авторизации нельзя создать.", "start": 1724955228367, "stop": 1724955228718, "uuid": "a921d63a-2665-4752-9cd4-772f724c992f", "historyId": "fcac8ed5c998ee107663d4ae01ed2476", "testCaseId": "fcac8ed5c998ee107663d4ae01ed2476", "fullName": "tests.test_order.TestOrder#test_create_order_without_auth", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order"}, {"name": "subSuite", "value": "TestOrder"}, {"name": "host", "value": "LAPTOP-74V5TFPG"}, {"name": "thread", "value": "8416-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order"}]}