{"name": "Неавторизованный пользователь не может изменить свои данные", "status": "passed", "description": "Проверка: статус 401, сообщение об ошибке при попытке изменения данных неавторизованным пользователем.", "start": 1724955239374, "stop": 1724955239730, "uuid": "b8cb912e-6322-4294-a4e8-4cd3e6ea732a", "historyId": "dec499270e631c48f862835cd9834e4d", "testCaseId": "dec499270e631c48f862835cd9834e4d", "fullName": "tests.test_user.TestUser#test_update_user_without_auth", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUser"}, {"name": "host", "value": "LAPTOP-74V5TFPG"}, {"name": "thread", "value": "8416-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user"}]}