{"name": "Получение заказа неавторизованного пользователя", "status": "failed", "statusDetails": {"message": "AssertionError: assert 200 == 401\n +  where 200 = <Response [200]>.status_code", "trace": "self = <tests.test_order.TestOrder object at 0x000002E82249EB50>\n\n    @allure.title('Получение заказа неавторизованного пользователя')\n    @allure.description('Проверка: статус 401, сообщение с ошибкой.')\n    def test_get_orders_without_auth(self):\n        response = requests.get(f\"{url.MAIN_URL}/orders\")\n    \n>       assert response.status_code == 401\nE       assert 200 == 401\nE        +  where 200 = <Response [200]>.status_code\n\ntests\\test_order.py:84: AssertionError"}, "description": "Проверка: статус 401, сообщение с ошибкой.", "start": 1724871110077, "stop": 1724871110784, "uuid": "6de6a6de-77b3-40cc-a0b9-5d0b8cd00990", "historyId": "d5b374693486e05eab322f9924cb1832", "testCaseId": "d5b374693486e05eab322f9924cb1832", "fullName": "tests.test_order.TestOrder#test_get_orders_without_auth", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order"}, {"name": "subSuite", "value": "TestOrder"}, {"name": "host", "value": "LAPTOP-74V5TFPG"}, {"name": "thread", "value": "16640-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order"}]}