{"name": "Логин с неверным логином и паролем", "status": "passed", "description": "Проверка:статус 401, сообщение об ошибке о некорректных данных.", "start": 1724955224387, "stop": 1724955226015, "uuid": "bb07f973-d15b-48ac-a4e2-2789de9cfdcc", "historyId": "666e64f1f50108a6aa8ce0b6292b7625", "testCaseId": "666e64f1f50108a6aa8ce0b6292b7625", "fullName": "tests.test_login_user.TestLoginUser#test_login_with_incorrect_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "LAPTOP-74V5TFPG"}, {"name": "thread", "value": "8416-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}